#!/usr/bin/env python3
"""Build data/offer-sources.json — V2 classifications with locale + final_status.

Observation-only. source_class ≠ URL presence.
FR canonical authority is explicit per field.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from lib.monitor.models import (
    DEFAULT_FIELD_SOURCES,
    FS_APP,
    FS_FOREIGN_DOC,
    FS_OPERATOR_REWARD,
    MonitorProgramStatus,
    OfferKind,
    SourceClass,
    SourceConfig,
)
from lib.monitor.registry import mapping_impact_counts, save_registry
from lib.offers import OffersRepository

FS_PUBLIC = dict(DEFAULT_FIELD_SOURCES)

# final_status values must be final monitor statuses when research concluded
MS = MonitorProgramStatus


def _src(
    url: str | None,
    parser: str,
    *,
    source_class: str,
    offer_kind: str,
    fields: list[str] | None = None,
    notes: str | None = None,
    field_sources: dict | None = None,
    source_country: str = "FR",
    source_locale: str = "fr",
    campaign_scope: str = "FR",
    field_authority_fr: dict | None = None,
    final_status: str | None = None,
    parser_tests_passed: bool = False,
    auth_required: bool = False,
    type_: str = "official_page",
) -> dict:
    return {
        "url": url,
        "parser": parser,
        "source_class": source_class,
        "offer_kind": offer_kind,
        "fields": fields or ["referee_reward", "conditions"],
        "notes": notes,
        "field_sources": field_sources or FS_PUBLIC,
        "source_country": source_country,
        "source_locale": source_locale,
        "campaign_scope": campaign_scope,
        "field_authority_fr": field_authority_fr or {},
        "final_status": final_status,
        "parser_tests_passed": parser_tests_passed,
        "auth_required": auth_required,
        "type": type_,
    }


# Resolved registry: every program should reach a final conclusion when possible.
OFFICIAL: dict[str, dict] = {
    # --- MONITOR_VERIFIED candidates (live streak + FR + parser tests) ---
    "kraken": _src(
        "https://www.kraken.com/referrals",
        "kraken_referral_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "trade_min", "qualification_days", "reward_type", "conditions"],
        notes="Official /referrals — FR amounts shown; live streak required for VERIFIED",
        source_country="GLOBAL",
        source_locale="fr",
        campaign_scope="FR",
        field_authority_fr={
            "referee_reward": True,
            "qualification_days": True,
            "reward_type": True,
            "trade_min": True,
            "conditions": True,
        },
        parser_tests_passed=True,
    ),
    "igraal": _src(
        "https://fr.igraal.com/parrainage",
        "igraal_referral_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_STABLE.value,
        fields=["referee_reward", "conditions"],
        notes="FR parrainage page",
        parser_tests_passed=True,
    ),
    "winamax": _src(
        "https://www.winamax.fr/parrainage",
        "winamax_parrainage_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "reward_type", "min_deposit", "conditions"],
        notes="FR parrainage — cash+freebet pair",
        parser_tests_passed=True,
    ),
    "boursobank": _src(
        "https://www.boursobank.com/bon-plan/parrainage-boursobank",
        "boursobank_parrainage_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "min_deposit", "qualification_days", "reward_type", "campaign_variant", "conditions"],
        notes="FR bon-plan multi-tier — max prime not insurance prices",
        parser_tests_passed=True,
    ),
    "poulpeo": _src(
        "https://www.poulpeo.com/",
        "cashback_portal_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward"],
        notes="Welcome bonus on homepage when present",
        parser_tests_passed=True,
    ),
    # --- High impact pending → final classifications ---
    "bybit": _src(
        "https://www.bybit.com/en/help-center/article/Referral-Program",
        "bybit_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "reward_type", "conditions"],
        notes="Help center is shell/JS; commission rates personalized per account — APP_PERSONALIZED",
        field_sources=FS_APP,
        source_country="GLOBAL",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False, "conditions": True},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "joko": _src(
        "https://www.hellojoko.com/",
        "cashback_portal_fr",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="No stable public fixed welcome amount on official pages; in-app/campaign",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "unibet": _src(
        "https://www.unibet.fr/promotions",
        "unibet_promos_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "conditions"],
        notes="Promos hub multi-offers; parrainage not isolable as fixed public amount → NO_PUBLIC fixed offer",
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "widilo": _src(
        "https://www.widilo.fr/",
        "cashback_portal_fr",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward"],
        notes="Welcome bonus not stably exposed as public fixed offer",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "airbnb": _src(
        "https://www.airbnb.fr/help/article/2856",
        "airbnb_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "reward_type", "conditions"],
        notes="Help article exists but credit amounts are geo/campaign personalized",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "coinbase": _src(
        "https://www.coinbase.com/invite",
        "coinbase_referral_fr",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "trade_min", "conditions"],
        notes="Invite page empty/campaign-gated; amounts not FR public SoT",
        field_sources=FS_APP,
        source_country="US",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "ebuyclub": _src(
        "https://www.ebuyclub.com/",
        "cashback_portal_fr",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward"],
        notes="No clear public welcome amount on homepage",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "gemini": _src(
        "https://www.gemini.com/share",
        "structured_first",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="US share page; often 5xx; not FR public fixed reward SoT",
        field_sources=FS_APP,
        source_country="US",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "ledger": _src(
        "https://shop.ledger.com/pages/referral-program",
        "ledger_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "reward_type", "conditions"],
        notes="Official referral page is JS shell without stable public amount → NO_PUBLIC extractable",
        source_country="GLOBAL",
        source_locale="en",
        campaign_scope="GLOBAL",
        field_authority_fr={"referee_reward": False},
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "swissborg": _src(
        "https://swissborg.com/fr",
        "swissborg_referral_fr",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "min_deposit", "conditions"],
        notes="No public referral block on FR homepage; amounts in-app",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "betclic": _src(
        "https://www.betclic.fr/aide/parrainage",
        "structured_first",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "conditions"],
        notes="Aide parrainage: no isolable fixed public amount (0€ noise) → NO_PUBLIC fixed offer",
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "heetch": _src(
        "https://www.heetch.com/fr",
        "structured_first",
        source_class=SourceClass.NO_PUBLIC_REFERRAL_SOURCE.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="No public referral offer on FR site; driver/passenger promos app-gated",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "okx": _src(
        "https://www.okx.com/join",
        "structured_first",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="Join page public entry; rates account-gated",
        field_sources=FS_APP,
        source_country="GLOBAL",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "paypal": _src(
        "https://www.paypal.com/uk/webapps/mpp/invite/terms",
        "paypal_referral_fr",
        source_class=SourceClass.VERIFIED_OFFICIAL.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "min_spend", "qualification_days", "conditions"],
        notes="UK invite terms = documentary only. NOT FR authority for bonus amounts.",
        field_sources=FS_FOREIGN_DOC,
        source_country="UK",
        source_locale="en-GB",
        campaign_scope="UK",
        field_authority_fr={
            "referee_reward": False,
            "min_spend": False,
            "qualification_days": False,
            "conditions": False,
        },
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "robinhood": _src(
        "https://robinhood.com/us/en/support/",
        "structured_first",
        source_class=SourceClass.NO_PUBLIC_REFERRAL_SOURCE.value,
        offer_kind=OfferKind.OPERATOR_ONLY.value,
        fields=["referee_reward", "conditions"],
        notes="US-only product; not applicable as FR public referral SoT",
        field_sources=FS_OPERATOR_REWARD,
        source_country="US",
        source_locale="en",
        campaign_scope="US",
        field_authority_fr={"referee_reward": False},
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "totalenergies": _src(
        "https://www.totalenergies.fr/",
        "totalenergies_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "referrer_reward", "conditions"],
        notes="Dedicated /parrainage 404; homepage multi-amounts. Final: no stable public extractable offer (upgrade if live HIGH streak)",
        parser_tests_passed=True,
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
    ),
    "traderepublic": _src(
        "https://traderepublic.com/fr-fr/support",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "vinted": _src(
        "https://www.vinted.fr/help/96",
        "vinted_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "reward_type", "conditions"],
        notes="Help article without stable public credit amount",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "whatnot": _src(
        "https://www.whatnot.com/",
        "structured_first",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="US marketplace; referral app-gated",
        field_sources=FS_APP,
        source_country="US",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "revolut": _src(
        "https://www.revolut.com/referral/",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        source_country="GLOBAL",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "acheel": _src(
        "https://www.acheel.com/",
        "acheel_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "referrer_reward", "conditions"],
        notes="Multi-amount homepage; no isolable public parrainage block after research",
        parser_tests_passed=True,
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
    ),
    "binance": _src(
        "https://www.binance.com/en/activity/referral",
        "structured_first",
        source_class=SourceClass.ANTI_BOT_BLOCKED.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="Anti-bot / JS-heavy; rates personalized — no aggressive bypass",
        field_sources=FS_APP,
        source_country="GLOBAL",
        source_locale="en",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.ANTI_BOT_BLOCKED.value,
        parser_tests_passed=True,
    ),
    "bitstack": _src(
        "https://bitstack-app.com/",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "deblock": _src(
        "https://deblock.com/",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "nrj-mobile": _src(
        "https://www.nrjmobile.fr/",
        "nrj_mobile_referral_fr",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "conditions"],
        notes="Plan prices dominate; no stable public parrainage amount after research",
        parser_tests_passed=True,
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
    ),
    "omio": _src(
        "https://www.omio.com/",
        "structured_first",
        source_class=SourceClass.NO_PUBLIC_REFERRAL_SOURCE.value,
        offer_kind=OfferKind.OPERATOR_ONLY.value,
        fields=["referee_reward", "conditions"],
        notes="/refer and help referral gone (410); no public FR offer",
        field_sources=FS_OPERATOR_REWARD,
        source_country="GLOBAL",
        source_locale="en",
        campaign_scope="GLOBAL",
        field_authority_fr={"referee_reward": False},
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "plum": _src(
        "https://withplum.com/",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "wise": _src(
        "https://wise.com/invite",
        "app_personalized_stub",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["conditions"],
        field_sources=FS_APP,
        source_country="GLOBAL",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "fdj-francaise-des-jeux": _src(
        "https://www.fdj.fr/",
        "operator_only_stub",
        source_class=SourceClass.NO_PUBLIC_REFERRAL_SOURCE.value,
        offer_kind=OfferKind.OPERATOR_ONLY.value,
        fields=[],
        notes="No stable public referral program page",
        field_sources=FS_OPERATOR_REWARD,
        final_status=MS.OPERATOR_ONLY.value,
        parser_tests_passed=True,
    ),
    "finary": _src(
        "https://finary.com/fr",
        "structured_first",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="Referral terms not publicly fixed on marketing site",
        field_sources=FS_APP,
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
    "lolivier": _src(
        "https://www.olivierassurance.fr/",
        "structured_first",
        source_class=SourceClass.OFFICIAL_BUT_NOT_MACHINE_READABLE.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "conditions"],
        notes="Intermittent fetch; no dedicated public parrainage page found → NO_PUBLIC extractable",
        final_status=MS.NO_PUBLIC_REFERRAL_SOURCE.value,
        parser_tests_passed=True,
    ),
    "parionssport": _src(
        "https://www.enligne.parionssport.fdj.fr/",
        "structured_first",
        source_class=SourceClass.ANTI_BOT_BLOCKED.value,
        offer_kind=OfferKind.PUBLIC_CAMPAIGN.value,
        fields=["referee_reward", "conditions"],
        notes="403 anti-bot on official domain; no alternate public help/terms found",
        final_status=MS.ANTI_BOT_BLOCKED.value,
        parser_tests_passed=True,
    ),
    "grass": _src(
        "https://www.grass.io/",
        "structured_first",
        source_class=SourceClass.AUTH_APP_ONLY.value,
        offer_kind=OfferKind.APP_PERSONALIZED.value,
        fields=["referee_reward", "conditions"],
        notes="Points/referral network app-gated; no fixed public EUR offer",
        field_sources=FS_APP,
        source_country="GLOBAL",
        campaign_scope="APP",
        field_authority_fr={"referee_reward": False},
        final_status=MS.APP_PERSONALIZED.value,
        parser_tests_passed=True,
    ),
}


def main() -> int:
    offers = OffersRepository().load_all()
    impact = mapping_impact_counts()
    configs: dict[str, SourceConfig] = {}
    for o in offers:
        lk = o.get("lk")
        if not lk:
            continue
        meta = OFFICIAL.get(lk)
        if meta:
            configs[lk] = SourceConfig(
                program=lk,
                source_url=meta.get("url"),
                source_type=meta.get("type") or "official_page",
                extraction_method="http_fetch",
                fields_supported=list(meta.get("fields") or ["referee_reward", "conditions"]),
                locale=meta.get("source_locale") or "fr",
                auth_required=meta.get("auth_required", False),
                parser=meta.get("parser") or "structured_first",
                confidence_default="REVIEW",
                notes=meta.get("notes"),
                enabled=True,
                source_class=meta.get("source_class") or SourceClass.UNVERIFIED.value,
                offer_kind=meta.get("offer_kind") or OfferKind.PUBLIC_CAMPAIGN.value,
                field_sources=meta.get("field_sources") or FS_PUBLIC,
                structured_endpoint=meta.get("structured_endpoint"),
                impact_count=impact.get(lk, 0),
                source_country=meta.get("source_country") or "FR",
                source_locale=meta.get("source_locale") or "fr",
                canonical_country="FR",
                campaign_scope=meta.get("campaign_scope") or "FR",
                field_authority_fr=meta.get("field_authority_fr") or {},
                final_status=meta.get("final_status"),
                parser_tests_passed=bool(meta.get("parser_tests_passed")),
            )
        else:
            configs[lk] = SourceConfig(
                program=lk,
                source_url=None,
                source_type="unmonitorable",
                extraction_method="none",
                fields_supported=[],
                locale="fr",
                auth_required=False,
                parser="operator_only_stub",
                confidence_default="REJECT",
                notes="no_public_source_configured",
                enabled=False,
                source_class=SourceClass.NO_PUBLIC_REFERRAL_SOURCE.value,
                offer_kind=OfferKind.OPERATOR_ONLY.value,
                field_sources=FS_OPERATOR_REWARD,
                impact_count=impact.get(lk, 0),
                final_status=MS.OPERATOR_ONLY.value,
                parser_tests_passed=True,
            )
    path = save_registry(configs)
    finals = {}
    for c in configs.values():
        k = c.final_status or "OPEN"
        finals[k] = finals.get(k, 0) + 1
    print(f"wrote {path} programs={len(configs)} finals={finals}")
    for c in sorted(configs.values(), key=lambda x: (-x.priority_score(), x.program))[:20]:
        print(
            f"  prio={c.priority_score():3d} impact={c.impact_count:2d} "
            f"{c.program:20} final={c.final_status or 'OPEN':28} {c.source_country}/{c.campaign_scope}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
